<?php

declare(strict_types=1);

namespace App\Libraries\Media;

use CodeIgniter\HTTP\Files\UploadedFile;
use Config\Database;
use Throwable;

/**
 * MediaService — validates and stores uploaded files privately under
 * writable/uploads, recording a `media_assets` row. Images are served back
 * through MediaController (`/media/<uuid>`), never linked directly. Pure
 * validation (`isAllowed`) is unit-tested.
 *
 * @see docs/architecture/24-ADMIN-PANEL.md
 */
final class MediaService
{
    private const MAX_BYTES = 15_728_640; // 15 MB (modern phone photos are 3–8 MB)
    private const ALLOWED   = [
        'image/jpeg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp', 'image/gif' => 'gif',
    ];
    private const DOC_MAX     = 10_485_760; // 10 MB
    private const DOC_ALLOWED = [
        'application/pdf' => 'pdf', 'application/msword' => 'doc',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'docx',
        'image/jpeg' => 'jpg', 'image/png' => 'png',
    ];

    /** Pure: is this mime+size an allowed product DOCUMENT (manual/warranty/etc.)? @return array{ok:bool,reason:string,ext:string} */
    public static function isAllowedDocument(string $mime, int $size): array
    {
        $mime = strtolower(trim($mime));
        if (! isset(self::DOC_ALLOWED[$mime])) {
            return ['ok' => false, 'reason' => 'Only PDF, DOC, DOCX, JPG or PNG documents are allowed.', 'ext' => ''];
        }
        if ($size <= 0 || $size > self::DOC_MAX) {
            return ['ok' => false, 'reason' => 'Document must be between 1 byte and 10 MB.', 'ext' => ''];
        }

        return ['ok' => true, 'reason' => '', 'ext' => self::DOC_ALLOWED[$mime]];
    }

    /** Pure: is this mime+size an allowed upload? @return array{ok:bool,reason:string,ext:string} */
    public static function isAllowed(string $mime, int $size): array
    {
        $mime = strtolower(trim($mime));
        if (! isset(self::ALLOWED[$mime])) {
            return ['ok' => false, 'reason' => 'Only JPG, PNG, WEBP or GIF images are allowed (HEIC/iPhone photos must be converted to JPG first).', 'ext' => ''];
        }
        if ($size <= 0 || $size > self::MAX_BYTES) {
            return ['ok' => false, 'reason' => 'Image must be between 1 byte and 15 MB.', 'ext' => ''];
        }

        return ['ok' => true, 'reason' => '', 'ext' => self::ALLOWED[$mime]];
    }

    /**
     * Validate + move an uploaded image, insert media_assets. Returns the asset
     * row (incl. uuid) or ['ok'=>false,'reason'=>...].
     * @return array<string,mixed>
     */
    public function store(UploadedFile $file, string $ownerType, ?int $ownerId, ?int $actorId, string $visibility = 'public', string $kind = 'image'): array
    {
        if (! $file->isValid() || $file->hasMoved()) {
            return ['ok' => false, 'reason' => 'Invalid upload.'];
        }
        $mime  = (string) $file->getMimeType();
        $size  = (int) $file->getSize();
        $check = $kind === 'document' ? self::isAllowedDocument($mime, $size) : self::isAllowed($mime, $size);
        if (! $check['ok']) {
            return $check;
        }

        $bytes = (string) @file_get_contents((string) ($file->getRealPath() ?: $file->getTempName()));
        if ($bytes === '') {
            return ['ok' => false, 'reason' => 'Invalid upload.'];
        }

        return $this->persist($bytes, $check['ext'], $mime, $ownerType, $ownerId, $visibility, $actorId);
    }

    /**
     * X2c — store GENERATED bytes (invoice/CN PDFs, label sheets, exports) as a
     * private media asset, mirroring store()'s layout and media_assets row.
     * @return array<string,mixed> {ok, id?, uuid?, object_key?, reason?}
     */
    public function storeBytes(string $bytes, string $ext, string $mime, string $ownerType, ?int $ownerId, ?int $actorId): array
    {
        if ($bytes === '') {
            return ['ok' => false, 'reason' => 'Empty document.'];
        }

        return $this->persist($bytes, $ext, $mime, $ownerType, $ownerId, 'private', $actorId);
    }

    /**
     * Store bytes, preferring S3 (test_s3) when configured and falling back to the
     * local writable/uploads layout. Records one media_assets row either way, so
     * the bucket column tells MediaController::serve how to read it back.
     * @return array<string,mixed>
     */
    private function persist(string $bytes, string $ext, string $mime, string $ownerType, ?int $ownerId, string $visibility, ?int $actorId): array
    {
        $uuid    = $this->uuid();
        $safe    = preg_replace('/[^a-z0-9_]/i', '', $ownerType) ?: 'misc';
        $ext     = preg_replace('/[^a-z0-9]/i', '', $ext) ?: 'bin';
        $vis     = $visibility === 'private' ? 'private' : 'public';
        $storage = service('documentStorage');

        // Preferred path — S3 (test_s3). object_key keeps a dated, owner-grouped layout.
        if ($storage->configured()) {
            $key = 'media/' . $safe . '/' . date('Y/m') . '/' . $uuid . '.' . $ext;
            if ($storage->putBytes($key, $bytes, $mime)) {
                return $this->record($uuid, $storage->bucket(), $key, $ownerType, $ownerId, $vis, $mime, strlen($bytes), $actorId);
            }
            log_message('warning', 'MediaService: S3 put failed, falling back to local for ' . $key);
        }

        // Fallback — local writable/uploads (also the path used in tests/dev).
        $dir = WRITEPATH . 'uploads/' . $safe;
        if (! is_dir($dir) && ! @mkdir($dir, 0775, true) && ! is_dir($dir)) {
            return ['ok' => false, 'reason' => 'Storage unavailable.'];
        }
        $objectKey = $safe . '/' . $uuid . '.' . $ext;
        if (file_put_contents($dir . '/' . $uuid . '.' . $ext, $bytes) === false) {
            return ['ok' => false, 'reason' => 'Could not write the file.'];
        }

        return $this->record($uuid, 'local', $objectKey, $ownerType, $ownerId, $vis, $mime, strlen($bytes), $actorId);
    }

    /** @return array<string,mixed> */
    private function record(string $uuid, string $bucket, string $objectKey, string $ownerType, ?int $ownerId, string $visibility, string $mime, int $size, ?int $actorId): array
    {
        try {
            Database::connect()->table('media_assets')->insert([
                'uuid' => $uuid, 'bucket' => mb_substr($bucket, 0, 80), 'object_key' => $objectKey,
                'owner_type' => mb_substr($ownerType, 0, 40), 'owner_id' => $ownerId,
                'visibility' => $visibility, 'mime' => mb_substr($mime, 0, 100), 'size_bytes' => $size,
                'status' => 'active', 'created_by' => $actorId,
            ]);

            return ['ok' => true, 'id' => (int) Database::connect()->insertID(), 'uuid' => $uuid, 'object_key' => $objectKey, 'mime' => $mime];
        } catch (Throwable) {
            return ['ok' => false, 'reason' => 'Could not store the file.'];
        }
    }

    private function uuid(): string
    {
        $d    = random_bytes(16);
        $d[6] = chr(ord($d[6]) & 0x0f | 0x40);
        $d[8] = chr(ord($d[8]) & 0x3f | 0x80);

        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($d), 4));
    }
}
